### ISSUE TITLE
Deneb support

### ISSUE THREAD

**Issue by michaelsproul** [sigp/eleel#22]
Before the Deneb hard fork rolls around we should implement the new Deneb engine API in `eleel` and test it on a devnet.

**Comment by Savid** [comment]
looks like we need this sooner rather than later. What do we need for this? Happy to help

I had a quick look but looks like we need to at least support `engine_newPayloadV3` with blobs bundles.

Do we need transition the deps from `https://github.com/michaelsproul/lighthouse` to `https://github.com/sigp/lighthouse` also?

**Comment by michaelsproul** [comment]
I can give this a go tomorrow. Helps having a live network to test on 😁 

Hope the fork mon isn't too broken! Let's try to stay ahead of future forks!

**Comment by barnabasbusa** [comment]
calling my dencun-devnet-12 not live? 😂

**Comment by michaelsproul** [comment]
> calling my dencun-devnet-12 not live?

doesn't have a `--network` flag 😉 

seriously though, I did intend to get this done, but here we are forking Goerli in Jan, and I didn't make it

**Comment by michaelsproul** [comment]
Implemented in #32

**Comment by Savid** [comment]
You're a weapon, tyvm
